export type Task={id:string;title:string;description:string;project:string;status:string;priority:string;due:string;created:string};
export type Project={id:string;name:string;color:string;description:string};
export type Note={id:string;name:string;content:string;updated:string};
export type Data={tasks:Task[];projects:Project[];notes:Note[]};
export const statuses=['Pending','In progress','In review','Success','Submitted','Failed','Expired'];
export const statusLabels:Record<string,string>={Pending:'Pendente','In progress':'Em andamento','In review':'Em revisão',Success:'Concluída',Submitted:'Enviada',Failed:'Falhou',Expired:'Expirada'};
export const seed:Data={projects:[{id:'p1',name:'Fintech Project',color:'#5874e8',description:'Uma experiência financeira mais simples.'},{id:'p2',name:'Brodo Redesign',color:'#9061d6',description:'Nova identidade e experiência digital.'},{id:'p3',name:'HR Setup',color:'#45a3b6',description:'Organização dos processos da equipe.'},{id:'p4',name:'artweb.so',color:'#ce66c6',description:'Nosso workspace de criação.'}],tasks:[
{id:'t1',title:'Preparar relatório do trimestre',description:'Consolidar os principais resultados e indicadores.',project:'p1',status:'In progress',priority:'Alta',due:'2026-09-10',created:'2026-09-07'},
{id:'t2',title:'Finalizar design da homepage',description:'Revisar os componentes e preparar o layout para desenvolvimento.',project:'p2',status:'In review',priority:'Alta',due:'2026-09-10',created:'2026-09-08'},
{id:'t3',title:'Revisar checklist de onboarding',description:'Verificar os passos de entrada de novos membros.',project:'p3',status:'Pending',priority:'Média',due:'2026-09-11',created:'2026-09-08'},
{id:'t4',title:'Organizar biblioteca de componentes',description:'Documentar variantes e estados dos componentes.',project:'p4',status:'In progress',priority:'Média',due:'2026-09-12',created:'2026-09-09'},
{id:'t5',title:'Validar fluxos de navegação',description:'Conferir o fluxo de tarefas, projetos e documentos.',project:'p4',status:'Pending',priority:'Baixa',due:'2026-09-15',created:'2026-09-09'},
{id:'t6',title:'Definir tokens de cores',description:'Paleta escura e cores semânticas aprovadas.',project:'p4',status:'Success',priority:'Média',due:'2026-09-09',created:'2026-09-07'},
{id:'t7',title:'Mapear jornadas do usuário',description:'Mapeamento da experiência principal concluído.',project:'p2',status:'Success',priority:'Média',due:'2026-09-08',created:'2026-09-07'},
{id:'t8',title:'Revisar modelos de dados',description:'Melhorar a estrutura dos dados e os relacionamentos.',project:'p1',status:'Pending',priority:'Média',due:'2026-09-14',created:'2026-09-10'}],notes:[{id:'n1',name:'readme.md',content:'# artweb.so\n\nUm espaço para transformar ideias em trabalho concluído.\n\n## Nosso fluxo\n\n1. Organize o trabalho em projetos.\n2. Crie tarefas com prioridade e prazo.\n3. Acompanhe o progresso no quadro.',updated:'2026-09-10'},{id:'n2',name:'design-system.md',content:'# Design system\n\nFundo: #1B1B1D\nSidebar: #161616\nSuperfície: #202022\nBorda: #333335\nDestaque: #5445F6\n\nTipografia neutra, ícones finos e espaços consistentes.',updated:'2026-09-10'}]};
