'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, Bot, Check, ChevronDown, CircleStop, Download, FileSearch, KeyRound, ListChecks, MessageSquarePlus, Paperclip, Send, Settings2, Sparkles, Target, UsersRound, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { Data } from '@/lib/model';

export type ConversationSummary={id:string;title:string;provider:string;model:string;pinned:number;createdAt:string;updatedAt:string};
type Source={id:string;type:string;title:string;detail:string;view:string};
type ChatMessage={id:string;role:'user'|'assistant';content:string;sources:Source[];createdAt?:string;pending?:boolean;error?:boolean};
type Credential={provider:string;model:string;endpoint:string;lastFour:string;updatedAt:string};
type ProviderOption={id:string;label:string;model:string;endpoint:string};

const providerLinks:Record<string,string>={openai:'https://platform.openai.com/api-keys',gemini:'https://aistudio.google.com/app/apikey',anthropic:'https://console.anthropic.com/settings/keys'};

function useConnections(){
  const [credentials,setCredentials]=useState<Credential[]>([]);const [providers,setProviders]=useState<ProviderOption[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  async function refresh(){setLoading(true);setError('');try{const response=await fetch('/api/ai/credentials');const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível carregar as conexões.');setCredentials(result.credentials||[]);setProviders(result.providers||[])}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível carregar as conexões.')}finally{setLoading(false)}}
  useEffect(()=>{let mounted=true;fetch('/api/ai/credentials').then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível carregar as conexões.');if(mounted){setCredentials(result.credentials||[]);setProviders(result.providers||[])}}).catch(reason=>{if(mounted)setError(reason instanceof Error?reason.message:'Não foi possível carregar as conexões.')}).finally(()=>{if(mounted)setLoading(false)});return()=>{mounted=false}},[]);return{credentials,providers,loading,error,refresh};
}

function ConnectionForm({credentials,providers,onSaved}:{credentials:Credential[];providers:ProviderOption[];onSaved:()=>void}){
  const first=providers[0];const [provider,setProvider]=useState('openai');const selected=providers.find(item=>item.id===provider)||first;const existing=credentials.find(item=>item.provider===provider);const [model,setModel]=useState(()=>credentials.find(item=>item.provider==='openai')?.model||providers.find(item=>item.id==='openai')?.model||first?.model||'');const [endpoint,setEndpoint]=useState(()=>credentials.find(item=>item.provider==='openai')?.endpoint||providers.find(item=>item.id==='openai')?.endpoint||first?.endpoint||'');const [apiKey,setApiKey]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [success,setSuccess]=useState(false);
  function chooseProvider(id:string){const option=providers.find(item=>item.id===id);const saved=credentials.find(item=>item.provider===id);setProvider(id);setModel(saved?.model||option?.model||'');setEndpoint(saved?.endpoint||option?.endpoint||'');setApiKey('');setMessage('');setSuccess(false)}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');setSuccess(false);try{const response=await fetch('/api/ai/credentials',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider,apiKey,model,endpoint})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível conectar.');setSuccess(true);setMessage('Conexão validada e protegida.');setApiKey('');await onSaved()}catch(reason){setMessage(reason instanceof Error?reason.message:'Não foi possível conectar.')}finally{setBusy(false)}}
  async function remove(){if(!existing)return;setBusy(true);const response=await fetch('/api/ai/credentials',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({provider})});setBusy(false);if(response.ok){setMessage('Conexão removida.');setSuccess(true);await onSaved()}else{const result=await response.json().catch(()=>({}));setMessage(result.error||'Não foi possível remover.')}}
  return <form className="ai-connection-form" onSubmit={save}>
    <div className="ai-provider-tabs">{providers.map(item=><button type="button" className={provider===item.id?'active':''} onClick={()=>chooseProvider(item.id)} key={item.id}>{item.label}</button>)}</div>
    <div className="ai-form-row"><label>Chave de API<div className="ai-secret-field"><KeyRound/><input type="password" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder={existing?`Conectada •••• ${existing.lastFour}`:'Cole sua chave de API'} autoComplete="off"/></div></label><label>Modelo<input value={model} onChange={event=>setModel(event.target.value)} placeholder={selected?.model}/></label></div>
    {provider==='compatible'&&<label>Endpoint compatível<input type="url" value={endpoint} onChange={event=>setEndpoint(event.target.value)} placeholder="https://api.exemplo.com/v1" required/></label>}
    <div className="ai-connection-note">A chave é testada antes de ser salva, fica cifrada no servidor e nunca volta completa ao navegador. O consumo será cobrado pelo provedor escolhido.</div>
    {message&&<div className={`ai-connection-message ${success?'success':'error'}`}>{success&&<Check/>}{message}</div>}
    <div className="ai-form-actions">{providerLinks[provider]&&<a href={providerLinks[provider]} target="_blank" rel="noreferrer">Como obter uma chave?</a>}<span/>{existing&&<button type="button" className="ai-remove-connection" disabled={busy} onClick={()=>void remove()}>Remover</button>}<button className="violet-button" disabled={busy||(!apiKey&&!existing)}>{busy?'Testando…':existing?'Atualizar conexão':'Testar e conectar'}</button></div>
  </form>;
}

export function AIConnectionSettings(){const state=useConnections();return <div className="ai-settings-connection">{state.loading?<div className="ai-settings-loading">Carregando conexões…</div>:state.error?<div className="ai-connection-message error">{state.error}</div>:<ConnectionForm credentials={state.credentials} providers={state.providers} onSaved={state.refresh}/>}</div>}

export function AgentChatView({data,selectedId,resetToken,onSelect,onHistoryChange,onNavigate}:{data:Data;selectedId:string|null;resetToken:number;onSelect:(id:string|null)=>void;onHistoryChange:(items:ConversationSummary[])=>void;onNavigate:(view:string)=>void}){
  const connections=useConnections();const [provider,setProvider]=useState('');const [messages,setMessages]=useState<ChatMessage[]>([]);const [conversationId,setConversationId]=useState<string|null>(null);const [draft,setDraft]=useState('');const [sending,setSending]=useState(false);const [status,setStatus]=useState('');const [configOpen,setConfigOpen]=useState(false);const [showJump,setShowJump]=useState(false);const scrollRef=useRef<HTMLDivElement>(null);const controllerRef=useRef<AbortController|null>(null);
  const active=connections.credentials.find(item=>item.provider===provider)||connections.credentials[0];
  useEffect(()=>{if(!provider&&connections.credentials[0])setProvider(connections.credentials[0].provider)},[connections.credentials,provider]);
  async function refreshHistory(){const response=await fetch('/api/ai/conversations');if(response.ok){const result=await response.json();onHistoryChange(result.conversations||[])}}
  useEffect(()=>{let mounted=true;fetch('/api/ai/conversations').then(async response=>{if(!response.ok)return;const result=await response.json();if(mounted)onHistoryChange(result.conversations||[])}).catch(()=>undefined);return()=>{mounted=false}},[onHistoryChange]);
  useEffect(()=>{setConversationId(null);setMessages([]);setStatus('');setDraft('')},[resetToken]);
  useEffect(()=>{if(!selectedId){if(conversationId) {setConversationId(null);setMessages([])}return}if(selectedId===conversationId)return;fetch(`/api/ai/conversations?id=${encodeURIComponent(selectedId)}`).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setConversationId(result.conversation.id);setProvider(result.conversation.provider);setMessages((result.messages||[]).map((message:ChatMessage)=>({...message,sources:message.sources||[]})))}).catch(()=>undefined)},[selectedId,conversationId]);
  useEffect(()=>{const node=scrollRef.current;if(!node)return;const nearBottom=node.scrollHeight-node.scrollTop-node.clientHeight<110;if(nearBottom){node.scrollTo({top:node.scrollHeight,behavior:sending?'smooth':'auto'});setShowJump(false)}else if(sending)setShowJump(true)},[messages,sending]);
  const suggestions=useMemo(()=>[
    {icon:ListChecks,title:'Planejar minha semana',text:`Analise minhas ${data.tasks.filter(item=>item.status!=='Success').length} tarefas abertas e organize a melhor ordem para esta semana.`,detail:'Prioridades, prazos e próximos passos'},
    {icon:UsersRound,title:data.leads.length?'Revisar oportunidades':'Começar pelo CRM',text:data.leads.length?'Revise meus leads e mostre quais próximos contatos precisam de atenção.':'Explique como organizar meus primeiros leads e clientes neste workspace.',detail:data.leads.length?`${data.leads.length} leads no workspace`:'Prepare a estrutura comercial'},
    {icon:Target,title:'Resumir meus projetos',text:'Resuma meus projetos, destaque riscos e recomende a próxima ação para cada um.',detail:`${data.projects.length} projetos disponíveis`},
    {icon:FileSearch,title:'Organizar notas e arquivos',text:'Leia minhas notas e arquivos, encontre decisões, pendências e conteúdos que deveriam virar tarefas.',detail:`${data.notes.length+data.memories.length} itens de conhecimento`},
  ],[data]);
  async function send(value=draft){const text=value.trim();if(!text||sending)return;if(!active){setConfigOpen(true);return}const userMessage:ChatMessage={id:crypto.randomUUID(),role:'user',content:text,sources:[]};const assistantId=crypto.randomUUID();setMessages(current=>[...current,userMessage,{id:assistantId,role:'assistant',content:'',sources:[],pending:true}]);setDraft('');setSending(true);setStatus('Preparando contexto');const aborter=new AbortController();controllerRef.current=aborter;
    try{const response=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({conversationId,provider:active.provider,message:text}),signal:aborter.signal});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.error||'Não foi possível enviar a mensagem.')}if(!response.body)throw new Error('O servidor não iniciou a resposta.');const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const item=JSON.parse(line);if(item.type==='meta'){setConversationId(item.conversationId);onSelect(item.conversationId);setMessages(current=>current.map(message=>message.id===assistantId?{...message,sources:item.sources||[]}:message))}else if(item.type==='status')setStatus(item.label);else if(item.type==='delta'){setStatus('Respondendo');setMessages(current=>current.map(message=>message.id===assistantId?{...message,content:message.content+item.text,pending:true}:message))}else if(item.type==='done'){setMessages(current=>current.map(message=>message.id===assistantId?{...message,pending:false,sources:item.sources||message.sources}:message))}else if(item.type==='error')throw new Error(item.message)}if(done)break}await refreshHistory()}catch(reason){if((reason as Error).name!=='AbortError')setMessages(current=>current.map(message=>message.id===assistantId?{...message,pending:false,error:true,content:message.content||((reason as Error).message||'Não foi possível gerar a resposta.')}:message))}finally{setSending(false);setStatus('');controllerRef.current=null}}
  function stop(){controllerRef.current?.abort();setSending(false);setStatus('');setMessages(current=>current.map(message=>message.pending?{...message,pending:false}:message))}
  function exportChat(){if(!messages.length)return;const content=messages.map(message=>`## ${message.role==='user'?'Você':'Assistente'}\n\n${message.content}\n`).join('\n');const blob=new Blob([content],{type:'text/markdown'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='conversa-artweb.md';anchor.click();URL.revokeObjectURL(url)}
  const quick=['O que precisa da minha atenção hoje?','Quais tarefas estão atrasadas?','Resuma o projeto mais ativo','Encontre decisões nas minhas notas'];
  return <div className="agent-page">
    <header className="agent-header"><div className="agent-provider"><Bot/><select value={active?.provider||provider} onChange={event=>setProvider(event.target.value)} aria-label="Provedor de IA"><option value="" disabled>Escolha sua IA</option>{connections.credentials.map(item=><option value={item.provider} key={item.provider}>{connections.providers.find(option=>option.id===item.provider)?.label||item.provider} · {item.model}</option>)}</select><ChevronDown/></div><div><button onClick={()=>{onSelect(null);setConversationId(null);setMessages([])}}><MessageSquarePlus/>Nova conversa</button><button onClick={exportChat} disabled={!messages.length}><Download/>Exportar</button><button onClick={()=>setConfigOpen(true)}><Settings2/>Configurar IA</button></div></header>
    <section className="agent-canvas">
      <div className="agent-scroll" ref={scrollRef} onScroll={event=>{const node=event.currentTarget;setShowJump(node.scrollHeight-node.scrollTop-node.clientHeight>110)}}>
        {!messages.length?<div className="agent-empty"><div className="agent-welcome"><Sparkles/><h1>Como posso ajudar no seu workspace?</h1><p>Consulte projetos, tarefas, clientes, notas e arquivos com fontes.</p></div><div className="agent-suggestions">{suggestions.map((item,index)=><button className={`agent-suggestion suggestion-${index+1}`} onClick={()=>void send(item.text)} key={item.title}><item.icon/><span><strong>{item.title}</strong><small>{item.detail}</small></span><Sparkles className="suggestion-star"/></button>)}</div></div>:<div className="agent-messages">{messages.map(message=><article className={`agent-message ${message.role} ${message.error?'error':''}`} key={message.id}><div className="agent-message-label">{message.role==='user'?'VOCÊ':'ARTWEB ASSISTENTE'}</div><div className="agent-message-content">{message.content||<span className="agent-typing"><i/><i/><i/></span>}{message.pending&&message.content&&<i className="agent-cursor"/>}</div>{message.sources.length>0&&message.role==='assistant'&&<div className="agent-sources"><span>Fontes usadas</span>{message.sources.map(source=><button onClick={()=>onNavigate(source.view)} key={`${source.type}-${source.id}`}><FileSearch/>{source.type} / {source.title}</button>)}</div>}</article>)}</div>}
      </div>
      {showJump&&<button className="agent-jump" onClick={()=>scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:'smooth'})}><ArrowDown/>Ir para a resposta</button>}
      <div className="agent-compose-wrap"><div className="agent-quick-prompts">{quick.map(item=><button onClick={()=>setDraft(item)} key={item}>{item}</button>)}</div>{!connections.loading&&!active&&<div className="agent-api-gate"><KeyRound/><div><strong>Conecte sua IA para começar</strong><p>Escolha OpenAI, Gemini, Claude ou outro serviço compatível e informe sua chave de API.</p></div><button className="violet-button" onClick={()=>setConfigOpen(true)}>Configurar minha IA</button></div>}<div className={`agent-composer ${sending?'sending':''}`}><textarea value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send()}}} placeholder={active?'Pergunte sobre seu workspace…':'Configure uma chave de API para conversar'} disabled={!active||sending} maxLength={12000} rows={1}/><button className="agent-send" onClick={()=>sending?stop():void send()} disabled={!sending&&(!active||!draft.trim())} aria-label={sending?'Parar resposta':'Enviar mensagem'}>{sending?<CircleStop/>:<Send/>}</button><div className="agent-composer-foot"><button disabled title="O contexto do workspace já é incluído automaticamente"><Paperclip/>Contexto do workspace incluído</button><span>{status||(active?`${connections.providers.find(item=>item.id===active.provider)?.label} · ${active.model}`:'Aguardando conexão')}</span></div></div></div>
    </section>
    <Dialog open={configOpen} onOpenChange={setConfigOpen}><DialogContent className="app-dialog ai-config-dialog"><DialogHeader><DialogTitle>Conectar uma IA</DialogTitle><DialogDescription>Use sua própria chave para ativar o assistente do ArtWeb OS.</DialogDescription></DialogHeader>{connections.loading?<div className="ai-settings-loading">Carregando…</div>:<ConnectionForm credentials={connections.credentials} providers={connections.providers} onSaved={async()=>{await connections.refresh();setConfigOpen(false)}}/>}<button className="ai-dialog-close" onClick={()=>setConfigOpen(false)} aria-label="Fechar"><X/></button></DialogContent></Dialog>
  </div>;
}
