'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, Brain, Building2, CalendarClock, Check, ChevronRight, CircleDollarSign, ContactRound, FileText, Folder, History, Mail, MapPin, Phone, Plus, Search, Sparkles, UserRound } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { leadStatuses, type Activity, type Client, type Data, type Importance, type Lead, type Memory, type Note } from '@/lib/model';

const today=()=>new Date().toISOString().slice(0,10);
const activity=(type:string,entityType:string,entityId:string,description:string):Activity=>({id:crypto.randomUUID(),type,entityType,entityId,description,created:new Date().toISOString()});

export function CRMView({data,onCommit}:{data:Data;onCommit:(data:Data)=>void}){
  const [dialog,setDialog]=useState(false);
  const [query,setQuery]=useState('');
  const leads=useMemo(()=>data.leads.filter(lead=>`${lead.company} ${lead.contact} ${lead.city} ${lead.segment}`.toLowerCase().includes(query.toLowerCase())),[data.leads,query]);
  function save(form:FormData){
    const company=String(form.get('company')||'').trim(); if(!company)return;
    const now=today();
    const lead:Lead={id:crypto.randomUUID(),company,contact:String(form.get('contact')||''),email:String(form.get('email')||''),phone:String(form.get('phone')||''),whatsapp:String(form.get('whatsapp')||''),instagram:String(form.get('instagram')||''),site:String(form.get('site')||''),segment:String(form.get('segment')||''),city:String(form.get('city')||''),source:String(form.get('source')||'Manual'),notes:String(form.get('notes')||''),potential:String(form.get('potential')||'Média') as Importance,status:'Encontrado',nextAction:String(form.get('nextAction')||''),created:now,updated:now};
    onCommit({...data,leads:[lead,...data.leads],activities:[activity('lead.created','lead',lead.id,`Lead ${company} adicionado ao CRM.`),...data.activities]});setDialog(false);
  }
  function advance(lead:Lead){
    const index=leadStatuses.indexOf(lead.status); if(index===leadStatuses.length-1)return;
    const status=leadStatuses[index+1];
    onCommit({...data,leads:data.leads.map(item=>item.id===lead.id?{...item,status,updated:today()}:item),activities:[activity('lead.status_changed','lead',lead.id,`${lead.company} avançou para ${status}.`),...data.activities]});
  }
  function convert(lead:Lead){
    const client:Client={id:crypto.randomUUID(),name:lead.contact||lead.company,company:lead.company,email:lead.email,phone:lead.phone||lead.whatsapp,domain:lead.site,hosting:'',services:'',monthlyFee:0,entryDate:today(),owner:'Você',status:'Ativo',leadId:lead.id};
    onCommit({...data,clients:[client,...data.clients],leads:data.leads.map(item=>item.id===lead.id?{...item,status:'Cliente',updated:today()}:item),activities:[activity('client.created','client',client.id,`${lead.company} convertido em cliente.`),...data.activities]});
  }
  return <div className="page-content"><ModuleHeading eyebrow="COMERCIAL" title="CRM e prospecção" detail={`${data.leads.length} leads · ${data.leads.filter(l=>l.status==='Proposta'||l.status==='Negociação').length} oportunidades abertas`} action={<button className="violet-button" onClick={()=>setDialog(true)}><Plus size={16}/>Novo lead</button>}/>
    <div className="module-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar empresa, cidade ou segmento"/></label><span>Pipeline comercial</span></div>
    <div className="crm-pipeline">{leadStatuses.map(status=><section className="crm-column" key={status}><header><span>{status}</span><b>{leads.filter(l=>l.status===status).length}</b></header><div>{leads.filter(l=>l.status===status).map(lead=><article className="lead-card" key={lead.id}><div className="lead-company"><span>{lead.company.slice(0,1).toUpperCase()}</span><div><strong>{lead.company}</strong><small>{lead.segment||'Segmento não informado'}</small></div></div><div className="lead-meta">{lead.city&&<span><MapPin/>{lead.city}</span>}{lead.contact&&<span><UserRound/>{lead.contact}</span>}{lead.nextAction&&<span><CalendarClock/>{lead.nextAction}</span>}</div><div className="lead-card-foot"><em className={`importance importance-${lead.potential.toLowerCase()}`}>{lead.potential}</em>{status==='Negociação'?<button onClick={()=>convert(lead)}>Converter<Check/></button>:status!=='Cliente'&&<button onClick={()=>advance(lead)}>Avançar<ChevronRight/></button>}</div></article>)}</div></section>)}</div>
    <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="app-dialog wide-dialog"><DialogHeader><DialogTitle>Novo lead</DialogTitle><DialogDescription>Cadastre uma oportunidade para acompanhar todo o histórico comercial.</DialogDescription></DialogHeader><form action={save} className="form-grid"><div className="form-row"><label>Empresa<input name="company" required autoFocus/></label><label>Responsável<input name="contact"/></label></div><div className="form-row"><label>E-mail<input name="email" type="email"/></label><label>Telefone<input name="phone"/></label></div><div className="form-row"><label>WhatsApp<input name="whatsapp"/></label><label>Instagram<input name="instagram" placeholder="@empresa"/></label></div><div className="form-row"><label>Site<input name="site" placeholder="https://"/></label><label>Cidade<input name="city"/></label></div><div className="form-row"><label>Segmento<input name="segment"/></label><label>Origem<select name="source"><option>Manual</option><option>Indicação</option><option>Instagram</option><option>Google</option><option>Evento</option></select></label></div><div className="form-row"><label>Potencial<select name="potential"><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></label><label>Próxima ação<input name="nextAction" type="date"/></label></div><label>Observações<textarea name="notes" rows={3}/></label><DialogFooter><button type="button" className="subtle-button dialog-button" onClick={()=>setDialog(false)}>Cancelar</button><button className="violet-button">Adicionar lead</button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}

export function ClientsView({data,onCommit,onNewProject}:{data:Data;onCommit:(data:Data)=>void;onNewProject:(clientId?:string)=>void}){
  const [dialog,setDialog]=useState(false);const [selected,setSelected]=useState<string>('');
  const client=data.clients.find(item=>item.id===selected)||data.clients[0];
  function save(form:FormData){const company=String(form.get('company')||'').trim();if(!company)return;const item:Client={id:crypto.randomUUID(),name:String(form.get('name')||company),company,email:String(form.get('email')||''),phone:String(form.get('phone')||''),domain:String(form.get('domain')||''),hosting:String(form.get('hosting')||''),services:String(form.get('services')||''),monthlyFee:Number(form.get('monthlyFee')||0),entryDate:today(),owner:'Você',status:'Ativo'};onCommit({...data,clients:[item,...data.clients],activities:[activity('client.created','client',item.id,`Cliente ${company} criado.`),...data.activities]});setSelected(item.id);setDialog(false)}
  return <div className="page-content"><ModuleHeading eyebrow="RELACIONAMENTOS" title="Clientes" detail={`${data.clients.filter(c=>c.status==='Ativo').length} clientes ativos`} action={<button className="violet-button" onClick={()=>setDialog(true)}><Plus size={16}/>Novo cliente</button>}/>{!client?<section className="empty-collection"><Building2/><h2>Cadastre seu primeiro cliente</h2><p>Centralize projetos, tarefas, contatos e conhecimento em uma única ficha.</p><button className="violet-button" onClick={()=>setDialog(true)}><Plus/>Novo cliente</button></section>:<div className="clients-layout"><div className="client-list">{data.clients.map(item=><button className={client.id===item.id?'active':''} key={item.id} onClick={()=>setSelected(item.id)}><span>{item.company.slice(0,1)}</span><div><strong>{item.company}</strong><small>{item.name}</small></div><em>{item.status}</em></button>)}</div><section className="client-detail panel"><header><div className="client-hero"><span>{client.company.slice(0,1)}</span><div><h2>{client.company}</h2><p>{client.name} · {client.status}</p></div></div><button className="subtle-button" onClick={()=>onNewProject(client.id)}><Plus/>Novo projeto</button></header><div className="client-kpis"><div><small>Projetos</small><strong>{data.projects.filter(p=>p.clientId===client.id).length}</strong></div><div><small>Tarefas abertas</small><strong>{data.tasks.filter(t=>t.clientId===client.id&&t.status!=='Success').length}</strong></div><div><small>Mensalidade</small><strong>{client.monthlyFee.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></div></div><div className="client-sections"><section><h3>Contato</h3><p><Mail/>{client.email||'Não informado'}</p><p><Phone/>{client.phone||'Não informado'}</p><p><Building2/>{client.domain||'Domínio não informado'}</p></section><section><h3>Serviços contratados</h3><p>{client.services||'Nenhum serviço cadastrado.'}</p><h3>Hospedagem</h3><p>{client.hosting||'Não informada.'}</p></section></div><div className="entity-history"><h3><History/>Histórico recente</h3>{data.activities.filter(a=>a.entityId===client.id).slice(0,5).map(item=><p key={item.id}>{item.description}<time>{new Date(item.created).toLocaleString('pt-BR')}</time></p>)}</div></section></div>}
    <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="app-dialog wide-dialog"><DialogHeader><DialogTitle>Novo cliente</DialogTitle><DialogDescription>Crie uma ficha central para todo o relacionamento.</DialogDescription></DialogHeader><form action={save} className="form-grid"><div className="form-row"><label>Empresa<input name="company" required autoFocus/></label><label>Contato principal<input name="name"/></label></div><div className="form-row"><label>E-mail<input name="email" type="email"/></label><label>Telefone<input name="phone"/></label></div><div className="form-row"><label>Domínio<input name="domain"/></label><label>Hospedagem<input name="hosting"/></label></div><div className="form-row"><label>Mensalidade<input name="monthlyFee" type="number" min="0" step="0.01"/></label><label>Serviços<input name="services"/></label></div><DialogFooter><button type="button" className="subtle-button dialog-button" onClick={()=>setDialog(false)}>Cancelar</button><button className="violet-button">Criar cliente</button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}

export function KnowledgeView({data,onCommit}:{data:Data;onCommit:(data:Data)=>void}){
  const [tab,setTab]=useState<'notes'|'memory'|'daily'>('notes');const [dialog,setDialog]=useState(false);
  function save(form:FormData){const mode=String(form.get('mode'));const title=String(form.get('title')||'').trim();if(!title)return;const now=new Date().toISOString();if(mode==='memory'){const item:Memory={id:crypto.randomUUID(),title,content:String(form.get('content')||''),importance:String(form.get('importance')||'Média') as Importance,source:String(form.get('source')||'user') as 'user'|'ai',tags:String(form.get('tags')||'').split(',').map(v=>v.trim()).filter(Boolean),created:now,updated:now};onCommit({...data,memories:[item,...data.memories],activities:[activity('memory.created','memory',item.id,`Memória “${title}” criada.`),...data.activities]})}else{const item:Note={id:crypto.randomUUID(),name:title.endsWith('.md')?title:`${title}.md`,content:String(form.get('content')||''),kind:String(form.get('source')||'user') as 'user'|'ai',importance:String(form.get('importance')||'Média') as Importance,category:String(form.get('category')||'Geral'),daily:mode==='daily',updated:today()};onCommit({...data,notes:[item,...data.notes],activities:[activity('note.created','note',item.id,`Nota “${item.name}” criada.`),...data.activities]})}setDialog(false)}
  function newDaily(){setTab('daily');setDialog(true)}
  const notes=data.notes.filter(n=>tab==='daily'?n.daily:!n.daily);
  return <div className="page-content"><ModuleHeading eyebrow="SEGUNDO CÉREBRO" title="Conhecimento" detail={`${data.notes.length} notas · ${data.memories.length} memórias`} action={<button className="violet-button" onClick={()=>setDialog(true)}><Plus/>Novo item</button>}/><div className="knowledge-tabs"><button className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}><FileText/>Notas</button><button className={tab==='memory'?'active':''} onClick={()=>setTab('memory')}><Brain/>Memórias</button><button className={tab==='daily'?'active':''} onClick={()=>setTab('daily')}><CalendarClock/>Daily Notes</button></div>{tab==='memory'?<div className="knowledge-grid">{data.memories.length?data.memories.map(item=><article className={`knowledge-card note-${item.source}`} key={item.id}><header><Brain/><span>{item.importance}</span></header><h2>{item.title}</h2><p>{item.content}</p><footer>{item.tags.map(tag=><em key={tag}>#{tag}</em>)}</footer></article>):<KnowledgeEmpty icon={Brain} title="Nenhuma memória ainda" text="Registre somente decisões e aprendizados que serão úteis no futuro." onNew={()=>setDialog(true)}/>}</div>:<div className="knowledge-grid">{notes.length?notes.map(item=><article className={`knowledge-card note-${item.kind||'user'}`} key={item.id}><header><FileText/><span>{item.importance||'Média'}</span></header><h2>{item.name}</h2><p>{item.content||'Nota vazia'}</p><footer><em>{item.daily?'Daily Note':item.category||'Geral'}</em><time>{item.updated}</time></footer></article>):<KnowledgeEmpty icon={tab==='daily'?CalendarClock:FileText} title={tab==='daily'?'Comece o registro de hoje':'Nenhuma nota ainda'} text={tab==='daily'?'Registre acontecimentos e pendências sem transformá-los automaticamente em memória.':'Notas do usuário aparecem em amarelo; notas da IA, em azul.'} onNew={tab==='daily'?newDaily:()=>setDialog(true)}/>}</div>}
    <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Novo item de conhecimento</DialogTitle><DialogDescription>Registre com contexto e promova somente o que merece ser reutilizado.</DialogDescription></DialogHeader><form action={save} className="form-grid"><label>Tipo<select name="mode" defaultValue={tab==='memory'?'memory':tab==='daily'?'daily':'note'}><option value="note">Nota</option><option value="memory">Memória</option><option value="daily">Daily Note</option></select></label><label>Título<input name="title" required autoFocus defaultValue={tab==='daily'?`Daily/${today().replaceAll('-','/')}`:''}/></label><label>Conteúdo Markdown<textarea name="content" rows={7}/></label><div className="form-row"><label>Origem<select name="source"><option value="user">Usuário</option><option value="ai">IA</option></select></label><label>Importância<select name="importance"><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></label></div><div className="form-row"><label>Categoria<input name="category"/></label><label>Tags<input name="tags" placeholder="wordpress, decisão"/></label></div><DialogFooter><button type="button" className="subtle-button dialog-button" onClick={()=>setDialog(false)}>Cancelar</button><button className="violet-button">Salvar</button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}

function KnowledgeEmpty({icon:Icon,title,text,onNew}:{icon:typeof Brain;title:string;text:string;onNew:()=>void}){return <section className="empty-collection"><Icon/><h2>{title}</h2><p>{text}</p><button className="violet-button" onClick={onNew}><Plus/>Criar item</button></section>}

type Result={id:string;type:string;title:string;detail:string;view:string;icon:typeof Search};
export function searchData(data:Data,query:string):Result[]{const q=query.trim().toLowerCase();if(!q)return[];const results:Result[]=[];const add=(id:string,type:string,title:string,detail:string,view:string,icon:typeof Search)=>{if(`${title} ${detail}`.toLowerCase().includes(q))results.push({id,type,title,detail,view,icon})};data.leads.forEach(x=>add(x.id,'Lead',x.company,`${x.contact} ${x.city} ${x.segment}`,'CRM',ContactRound));data.clients.forEach(x=>add(x.id,'Cliente',x.company,`${x.name} ${x.email}`,'Clientes',Building2));data.projects.forEach(x=>add(x.id,'Projeto',x.name,x.description,'Projetos',Folder));data.tasks.forEach(x=>add(x.id,'Tarefa',x.title,x.description,'Tarefas',Check));data.notes.forEach(x=>add(x.id,'Nota',x.name,x.content,'Conhecimento',FileText));data.memories.forEach(x=>add(x.id,'Memória',x.title,`${x.content} ${x.tags.join(' ')}`,'Conhecimento',Brain));return results.slice(0,30)}

export function SearchView({data,query,setQuery,onNavigate}:{data:Data;query:string;setQuery:(value:string)=>void;onNavigate:(view:string)=>void}){const results=searchData(data,query);return <div className="page-content"><ModuleHeading eyebrow="TODO O SISTEMA" title="Busca global" detail="Clientes, leads, projetos, tarefas, notas e memórias"/><label className="global-search-box"><Search/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ex.: filtro Mercado Rufino"/><kbd>Ctrl K</kbd></label><SearchResults results={results} query={query} onNavigate={onNavigate}/></div>}

export function CommandPalette({open,onOpenChange,data,onNavigate,onQuick}:{open:boolean;onOpenChange:(open:boolean)=>void;data:Data;onNavigate:(view:string)=>void;onQuick:(kind:string)=>void}){const [query,setQuery]=useState('');const results=searchData(data,query);const commands=[['Novo lead','lead'],['Novo cliente','client'],['Novo projeto','project'],['Nova tarefa','task'],['Criar nota','note'],['Abrir CRM','CRM'],['Abrir conhecimento','Conhecimento']];function close(value:boolean){if(!value)setQuery('');onOpenChange(value)}function run(value:string){if(value==='CRM'||value==='Conhecimento')onNavigate(value);else onQuick(value);close(false)}return <Dialog open={open} onOpenChange={close}><DialogContent className="command-dialog app-dialog"><label className="command-input"><Search/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar ou digitar um comando…"/></label>{query?<SearchResults results={results} query={query} onNavigate={view=>{onNavigate(view);close(false)}}/>:<div className="command-list"><small>AÇÕES RÁPIDAS</small>{commands.map(([label,value])=><button key={value} onClick={()=>run(value)}><Sparkles/>{label}<ArrowRight/></button>)}</div>}</DialogContent></Dialog>}

function SearchResults({results,query,onNavigate}:{results:Result[];query:string;onNavigate:(view:string)=>void}){if(!query)return <div className="search-empty">Digite para pesquisar todo o workspace.</div>;if(!results.length)return <div className="search-empty">Nenhum resultado encontrado para “{query}”.</div>;return <div className="search-results">{results.map(result=><button key={`${result.type}-${result.id}`} onClick={()=>onNavigate(result.view)}><span><result.icon/></span><div><small>{result.type}</small><strong>{result.title}</strong><p>{result.detail}</p></div><ChevronRight/></button>)}</div>}

export function OperationsStrip({data,onNavigate}:{data:Data;onNavigate:(view:string)=>void}){const overdue=data.tasks.filter(t=>t.status!=='Success'&&t.due<today()).length;const waiting=data.leads.filter(l=>l.status==='Contatado'||l.status==='Respondeu').length;const proposals=data.leads.filter(l=>l.status==='Proposta'||l.status==='Negociação').length;return <section className="operations-strip"><button onClick={()=>onNavigate('CRM')}><ContactRound/><span>Leads aguardando ação<strong>{waiting}</strong></span></button><button onClick={()=>onNavigate('Tarefas')}><CalendarClock/><span>Tarefas atrasadas<strong>{overdue}</strong></span></button><button onClick={()=>onNavigate('CRM')}><CircleDollarSign/><span>Propostas abertas<strong>{proposals}</strong></span></button><button onClick={()=>onNavigate('Clientes')}><Building2/><span>Clientes ativos<strong>{data.clients.filter(c=>c.status==='Ativo').length}</strong></span></button></section>}

function ModuleHeading({eyebrow,title,detail,action}:{eyebrow:string;title:string;detail:string;action?:React.ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}<span className="wave">✳</span></h1><p>{detail}</p></div>{action}</div>}
