'use client';

import { useEffect, useMemo, useState } from 'react';
import { Building2, Check, CircleAlert, ExternalLink, History, KeyRound, LoaderCircle, MapPin, Phone, Plus, Search, Settings2, ShieldCheck, Star, Trash2 } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { Activity, Data, Importance, Lead } from '@/lib/model';

type Prospect={id:string;name:string;category:string;address:string;phone:string;rating:number;reviewCount:number;mapsUrl:string;businessStatus:string;score:number};
type SearchHistory={id:string;category:string;location:string;minRating:number;minReviews:number;resultCount:number;createdAt:string};
type Connection={connected:boolean;lastFour:string;updatedAt:string};

const categories=['Clínicas odontológicas','Clínicas de estética','Psicólogos e terapeutas','Academias e estúdios','Restaurantes e cafeterias','Advogados','Contadores','Arquitetos','Imobiliárias','Escolas e cursos','Oficinas automotivas','Salões e barbearias'];
const normalize=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\W/g,'');

function usePlacesConnection(){
  const [connection,setConnection]=useState<Connection>({connected:false,lastFour:'',updatedAt:''});const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  async function refresh(){setLoading(true);setError('');try{const response=await fetch('/api/prospecting/credentials');const result=await response.json();if(!response.ok)throw new Error(result.error);setConnection(result)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível carregar a conexão.')}finally{setLoading(false)}}
  useEffect(()=>{let mounted=true;fetch('/api/prospecting/credentials').then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);if(mounted)setConnection(result)}).catch(reason=>{if(mounted)setError(reason instanceof Error?reason.message:'Não foi possível carregar a conexão.')}).finally(()=>{if(mounted)setLoading(false)});return()=>{mounted=false}},[]);return{connection,loading,error,refresh};
}

function PlacesConnectionForm({state,onSaved}:{state:Connection;onSaved:()=>void}){
  const [apiKey,setApiKey]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [success,setSuccess]=useState(false);
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');setSuccess(false);try{const response=await fetch('/api/prospecting/credentials',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({apiKey})});const result=await response.json();if(!response.ok)throw new Error(result.error);setApiKey('');setMessage('Fonte conectada e chave protegida.');setSuccess(true);await onSaved()}catch(reason){setMessage(reason instanceof Error?reason.message:'Não foi possível conectar.')}finally{setBusy(false)}}
  async function remove(){setBusy(true);const response=await fetch('/api/prospecting/credentials',{method:'DELETE'});setBusy(false);if(response.ok){setMessage('Conexão removida.');setSuccess(true);await onSaved()}else{const result=await response.json().catch(()=>({}));setMessage(result.error||'Não foi possível remover.')}}
  return <form className="places-connection" onSubmit={save}>
    <div className="places-connection-head"><span><MapPin/></span><div><strong>Google Places API (New)</strong><p>Fonte de empresas, avaliações, telefone e presença de site.</p></div>{state.connected&&<em><Check/>Conectado •••• {state.lastFour}</em>}</div>
    <label>Chave da API<div><KeyRound/><input type="password" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder={state.connected?'Cole uma nova chave para substituir':'Cole a chave do Google Places'} autoComplete="off"/></div></label>
    <div className="places-security"><ShieldCheck/><span>A chave será testada, cifrada no servidor e nunca será exibida novamente. As consultas podem gerar cobrança na sua conta Google Cloud.</span></div>
    {message&&<div className={`places-message ${success?'success':'error'}`}>{message}</div>}
    <div className="places-actions"><a href="https://console.cloud.google.com/google/maps-apis/credentials" target="_blank" rel="noreferrer">Abrir credenciais do Google Cloud<ExternalLink/></a><span/>{state.connected&&<button type="button" className="danger-text" onClick={()=>void remove()} disabled={busy}><Trash2/>Remover</button>}<button className="violet-button" disabled={busy||!apiKey.trim()}>{busy?'Testando…':state.connected?'Atualizar conexão':'Testar e conectar'}</button></div>
  </form>;
}

export function ProspectingConnectionSettings(){const state=usePlacesConnection();return <div className="prospecting-settings">{state.loading?<div className="prospecting-loading"><LoaderCircle/>Carregando conexão…</div>:state.error?<div className="places-message error">{state.error}</div>:<PlacesConnectionForm state={state.connection} onSaved={state.refresh}/>}</div>}

export function ProspectingPanel({data,onCommit}:{data:Data;onCommit:(data:Data)=>void}){
  const connection=usePlacesConnection();const [category,setCategory]=useState(categories[0]);const [location,setLocation]=useState('');const [minRating,setMinRating]=useState('4.5');const [minReviews,setMinReviews]=useState('20');const [phoneOnly,setPhoneOnly]=useState(false);const [searching,setSearching]=useState(false);const [error,setError]=useState('');const [results,setResults]=useState<Prospect[]>([]);const [analyzed,setAnalyzed]=useState(0);const [searched,setSearched]=useState(false);const [configOpen,setConfigOpen]=useState(false);const [importing,setImporting]=useState<Prospect|null>(null);const [history,setHistory]=useState<SearchHistory[]>([]);
  useEffect(()=>{fetch('/api/prospecting/search').then(async response=>response.ok?response.json():{searches:[]}).then(result=>setHistory(result.searches||[])).catch(()=>undefined)},[]);
  const existingIds=useMemo(()=>new Set(data.leads.map(lead=>lead.externalId).filter(Boolean)),[data.leads]);
  const existingNames=useMemo(()=>new Set(data.leads.map(lead=>normalize(lead.company))),[data.leads]);
  const duplicates=results.filter(item=>existingIds.has(item.id)||existingNames.has(normalize(item.name))).length;
  async function search(event?:React.FormEvent){event?.preventDefault();if(!connection.connection.connected){setConfigOpen(true);return}setSearching(true);setError('');setSearched(true);try{const response=await fetch('/api/prospecting/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({category,location,minRating:Number(minRating),minReviews:Number(minReviews),phoneOnly})});const result=await response.json();if(!response.ok)throw new Error(result.error);setResults(result.matches||[]);setAnalyzed(result.analyzed||0);const item:SearchHistory={id:crypto.randomUUID(),category,location,minRating:Number(minRating),minReviews:Number(minReviews),resultCount:(result.matches||[]).length,createdAt:result.searchedAt};setHistory(current=>[item,...current].slice(0,8))}catch(reason){setResults([]);setAnalyzed(0);setError(reason instanceof Error?reason.message:'Não foi possível pesquisar.')}finally{setSearching(false)}}
  function reuse(item:SearchHistory){setCategory(item.category);setLocation(item.location);setMinRating(String(item.minRating));setMinReviews(String(item.minReviews))}
  function addLead(form:FormData){if(!importing)return;const now=new Date();const nextAction=new Date(now.getTime()+2*86400000).toISOString().slice(0,10);const score=importing.score;const potential:Importance=score>=80?'Crítica':score>=65?'Alta':score>=50?'Média':'Baixa';const company=String(form.get('company')||importing.name).trim();const lead:Lead={id:crypto.randomUUID(),company,contact:String(form.get('contact')||''),email:'',phone:String(form.get('phone')||importing.phone),whatsapp:'',instagram:'',site:'',segment:String(form.get('segment')||importing.category),city:String(form.get('city')||location),source:'Prospecção Google Places',notes:String(form.get('notes')||''),potential,status:'Encontrado',nextAction,created:now.toISOString().slice(0,10),updated:now.toISOString().slice(0,10),externalId:importing.id,rating:importing.rating,reviewCount:importing.reviewCount,mapsUrl:importing.mapsUrl};const log:Activity={id:crypto.randomUUID(),type:'lead.prospected',entityType:'lead',entityId:lead.id,description:`${company} foi encontrado na prospecção e adicionado ao CRM.`,created:now.toISOString()};onCommit({...data,leads:[lead,...data.leads],activities:[log,...data.activities]});setImporting(null)}
  return <div className="prospecting-panel">
    <div className="prospecting-intro"><div><span>BUSCA QUALIFICADA</span><h2>Encontre empresas com oportunidade digital</h2><p>Somente negócios bem avaliados e sem site informado na fonte consultada.</p></div><button className="subtle-button" onClick={()=>setConfigOpen(true)}><Settings2/>Configurar fonte</button></div>
    <form className="prospecting-filters" onSubmit={search}><label>Categoria<input list="prospecting-categories" value={category} onChange={event=>setCategory(event.target.value)} required/><datalist id="prospecting-categories">{categories.map(item=><option value={item} key={item}/>)}</datalist></label><label className="location-field">Cidade ou região<div><MapPin/><input value={location} onChange={event=>setLocation(event.target.value)} placeholder="Ex.: Campinas, SP" required/></div></label><label>Nota mínima<select value={minRating} onChange={event=>setMinRating(event.target.value)}><option value="4">4,0+</option><option value="4.3">4,3+</option><option value="4.5">4,5+</option><option value="4.7">4,7+</option><option value="4.8">4,8+</option></select></label><label>Avaliações mínimas<input type="number" value={minReviews} onChange={event=>setMinReviews(event.target.value)} min="0" max="10000"/></label><label className="phone-filter"><input type="checkbox" checked={phoneOnly} onChange={event=>setPhoneOnly(event.target.checked)}/><span>Com telefone</span></label><button className="violet-button prospecting-search" disabled={searching}>{searching?<><LoaderCircle/>Pesquisando…</>:<><Search/>Buscar oportunidades</>}</button></form>
    {!connection.loading&&!connection.connection.connected&&<section className="prospecting-gate"><KeyRound/><div><strong>Conecte uma fonte de empresas</strong><p>Cadastre uma chave do Google Places para iniciar buscas. A chave do Gemini não é usada nessa ferramenta.</p></div><button className="violet-button" onClick={()=>setConfigOpen(true)}>Configurar Google Places</button></section>}
    {error&&<div className="prospecting-error"><CircleAlert/><span>{error}</span><button onClick={()=>void search()}>Tentar novamente</button></div>}
    {searched&&!error&&<div className="prospecting-kpis"><div><small>Empresas analisadas</small><strong>{analyzed}</strong></div><div><small>Oportunidades encontradas</small><strong>{results.length}</strong></div><div><small>Nota média</small><strong>{results.length?(results.reduce((sum,item)=>sum+item.rating,0)/results.length).toFixed(1):'—'}</strong></div><div><small>Já estavam no CRM</small><strong>{duplicates}</strong></div></div>}
    {searching?<section className="prospecting-empty"><LoaderCircle className="spin"/><h3>Analisando empresas</h3><p>Verificando reputação, avaliações e presença de site.</p></section>:searched&&!error&&!results.length?<section className="prospecting-empty"><Search/><h3>Nenhuma oportunidade corresponde aos filtros</h3><p>Reduza a nota mínima, diminua o número de avaliações ou amplie a região.</p></section>:results.length>0?<div className="prospecting-results"><header><div><strong>{results.length} oportunidades</strong><span>Ordenadas pelo potencial de presença digital</span></div><small>“Sem site” significa que a fonte não informou um website.</small></header><div className="prospecting-table"><div className="prospecting-row prospecting-table-head"><span>Empresa</span><span>Reputação</span><span>Contato</span><span>Oportunidade</span><span/></div>{results.map(item=>{const duplicate=existingIds.has(item.id)||existingNames.has(normalize(item.name));return <article className="prospecting-row" key={item.id}><div className="prospecting-company"><i>{item.name.slice(0,1).toUpperCase()}</i><span><strong>{item.name}</strong><small><MapPin/>{item.address||'Endereço não informado'}</small><em>{item.category}</em></span></div><div className="prospecting-rating"><strong><Star/>{item.rating.toFixed(1)}</strong><small>{item.reviewCount.toLocaleString('pt-BR')} avaliações</small></div><div className="prospecting-contact"><span><Phone/>{item.phone||'Sem telefone'}</span>{item.mapsUrl&&<a href={item.mapsUrl} target="_blank" rel="noreferrer">Ver no mapa<ExternalLink/></a>}</div><div className="prospecting-score"><strong>{item.score}</strong><span>{item.score>=80?'Alta':item.score>=65?'Boa':'Revisar'}</span><em>Sem site identificado</em></div><div>{duplicate?<button className="already-added" disabled><Check/>Já está no CRM</button>:<button className="violet-button" onClick={()=>setImporting(item)}><Plus/>Adicionar lead</button>}</div></article>})}</div></div>:<section className="prospecting-empty prospecting-start"><Building2/><h3>Comece por uma categoria e região</h3><p>O ArtWeb filtrará empresas com boa reputação e sem site identificado.</p></section>}
    {history.length>0&&<section className="prospecting-history"><h3><History/>Pesquisas recentes</h3><div>{history.map(item=><button onClick={()=>reuse(item)} key={item.id}><strong>{item.category}</strong><span>{item.location} · {item.minRating}+ · {item.resultCount} resultados</span><time>{new Date(item.createdAt).toLocaleDateString('pt-BR')}</time></button>)}</div></section>}
    <Dialog open={configOpen} onOpenChange={setConfigOpen}><DialogContent className="app-dialog ai-config-dialog"><DialogHeader><DialogTitle>Configurar fonte de empresas</DialogTitle><DialogDescription>Conecte o Google Places ao módulo de prospecção.</DialogDescription></DialogHeader>{connection.loading?<div className="prospecting-loading"><LoaderCircle/>Carregando…</div>:<PlacesConnectionForm state={connection.connection} onSaved={async()=>{await connection.refresh();setConfigOpen(false)}}/>}</DialogContent></Dialog>
    <Dialog open={!!importing} onOpenChange={open=>!open&&setImporting(null)}><DialogContent className="app-dialog wide-dialog"><DialogHeader><DialogTitle>Adicionar oportunidade ao CRM</DialogTitle><DialogDescription>Revise os dados antes de criar o lead.</DialogDescription></DialogHeader>{importing&&<form action={addLead} className="form-grid"><div className="prospect-preview"><span><Star/>{importing.rating.toFixed(1)} · {importing.reviewCount} avaliações</span><em>Sem site identificado</em></div><div className="form-row"><label>Empresa<input name="company" defaultValue={importing.name} required/></label><label>Contato responsável<input name="contact" placeholder="Pesquisar depois"/></label></div><div className="form-row"><label>Telefone<input name="phone" defaultValue={importing.phone}/></label><label>Cidade ou região<input name="city" defaultValue={location}/></label></div><label>Segmento<input name="segment" defaultValue={importing.category}/></label><label>Observações<textarea name="notes" rows={4} defaultValue={`Nota ${importing.rating.toFixed(1)} com ${importing.reviewCount} avaliações. Endereço: ${importing.address}. ${importing.mapsUrl?`Google Maps: ${importing.mapsUrl}`:''}`}/></label><DialogFooter><button type="button" className="subtle-button dialog-button" onClick={()=>setImporting(null)}>Cancelar</button><button className="violet-button">Adicionar ao pipeline</button></DialogFooter></form>}</DialogContent></Dialog>
  </div>;
}
