'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { Building2, Check, CircleAlert, Download, ExternalLink, Globe2, History, KeyRound, LoaderCircle, MapPin, Phone, Plus, Search, Settings2, ShieldCheck, Star, Trash2, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { Activity, Data, Importance, Lead } from '@/lib/model';

type Size='local'|'small'|'medium'|'large';
type Prospect={id:string;name:string;category:string;address:string;phone:string;rating:number;reviewCount:number;websiteUrl:string;mapsUrl:string;businessStatus:string;size:Size;score:number};
type SearchHistory={id:string;category:string;location:string;minRating:number;minReviews:number;resultCount:number;createdAt:string};
type Connection={connected:boolean;lastFour:string;updatedAt:string};
type Cursor={queryIndex:number;pageToken?:string};
type Batch={matches:Prospect[];analyzed:number;searchId:string;nextCursor:Cursor|null;exhausted:boolean;queryProgress:{current:number;total:number};error?:string};
type Sort='score'|'reviews'|'rating'|'name';

const categories=['Clínicas odontológicas','Clínicas de estética','Psicólogos e terapeutas','Academias e estúdios','Restaurantes e cafeterias','Advogados','Contadores','Arquitetos','Imobiliárias','Escolas e cursos','Oficinas automotivas','Salões e barbearias'];
const normalize=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\W/g,'');
const splitEntries=(value:string)=>[...new Set(value.split(/[\n;]+/).map(item=>item.trim()).filter(Boolean))];
const sizeLabels:Record<Size,string>={local:'Local',small:'Pequeno',medium:'Médio',large:'Grande'};
const sleep=(duration:number)=>new Promise(resolve=>setTimeout(resolve,duration));

function usePlacesConnection(){
  const [connection,setConnection]=useState<Connection>({connected:false,lastFour:'',updatedAt:''});const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  async function refresh(){setLoading(true);setError('');try{const response=await fetch('/api/prospecting/credentials');const result=await response.json() as Connection&{error?:string};if(!response.ok)throw new Error(result.error);setConnection(result)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível carregar a conexão.')}finally{setLoading(false)}}
  useEffect(()=>{let mounted=true;fetch('/api/prospecting/credentials').then(async response=>{const result=await response.json() as Connection&{error?:string};if(!response.ok)throw new Error(result.error);if(mounted)setConnection(result)}).catch(reason=>{if(mounted)setError(reason instanceof Error?reason.message:'Não foi possível carregar a conexão.')}).finally(()=>{if(mounted)setLoading(false)});return()=>{mounted=false}},[]);return{connection,loading,error,refresh};
}

function PlacesConnectionForm({state,onSaved}:{state:Connection;onSaved:()=>void}){
  const [apiKey,setApiKey]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [success,setSuccess]=useState(false);
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');setSuccess(false);try{const response=await fetch('/api/prospecting/credentials',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({apiKey})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error);setApiKey('');setMessage('Fonte conectada e chave protegida.');setSuccess(true);await onSaved()}catch(reason){setMessage(reason instanceof Error?reason.message:'Não foi possível conectar.')}finally{setBusy(false)}}
  async function remove(){setBusy(true);const response=await fetch('/api/prospecting/credentials',{method:'DELETE'});setBusy(false);if(response.ok){setMessage('Conexão removida.');setSuccess(true);await onSaved()}else{const result=await response.json().catch(()=>({})) as {error?:string};setMessage(result.error||'Não foi possível remover.')}}
  return <form className="places-connection" onSubmit={save}>
    <div className="places-connection-head"><span><MapPin/></span><div><strong>Google Places API (New)</strong><p>Fonte de empresas, avaliações, telefone e presença de site.</p></div>{state.connected&&<em><Check/>Conectado •••• {state.lastFour}</em>}</div>
    <label>Chave da API<div><KeyRound/><input type="password" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder={state.connected?'Cole uma nova chave para substituir':'Cole a chave do Google Places'} autoComplete="off"/></div></label>
    <div className="places-security"><ShieldCheck/><span>A chave será testada, cifrada no servidor e nunca será exibida novamente. As consultas podem gerar cobrança na sua conta Google Cloud.</span></div>
    {message&&<div className={`places-message ${success?'success':'error'}`}>{message}</div>}
    <div className="places-actions"><a href="https://console.cloud.google.com/google/maps-apis/credentials" target="_blank" rel="noreferrer">Abrir credenciais do Google Cloud<ExternalLink/></a><span/>{state.connected&&<button type="button" className="danger-text" onClick={()=>void remove()} disabled={busy}><Trash2/>Remover</button>}<button className="violet-button" disabled={busy||!apiKey.trim()}>{busy?'Testando…':state.connected?'Atualizar conexão':'Testar e conectar'}</button></div>
  </form>;
}

export function ProspectingConnectionSettings(){const state=usePlacesConnection();return <div className="prospecting-settings">{state.loading?<div className="prospecting-loading"><LoaderCircle/>Carregando conexão…</div>:state.error?<div className="places-message error">{state.error}</div>:<PlacesConnectionForm state={state.connection} onSaved={state.refresh}/>}</div>}

export function ProspectingPanel({data,onCommit}:{data:Data;onCommit:(data:Data)=>void}){
  const connection=usePlacesConnection();const controllerRef=useRef<AbortController|null>(null);
  const [categoryInput,setCategoryInput]=useState(categories[0]);const [locationInput,setLocationInput]=useState('');const [minRating,setMinRating]=useState('4.5');const [minReviews,setMinReviews]=useState('20');const [websitePresence,setWebsitePresence]=useState('without');const [businessSize,setBusinessSize]=useState('any');const [phoneOnly,setPhoneOnly]=useState(false);const [operationalOnly,setOperationalOnly]=useState(true);const [targetCount,setTargetCount]=useState('500');const [sort,setSort]=useState<Sort>('score');
  const [searching,setSearching]=useState(false);const [error,setError]=useState('');const [results,setResults]=useState<Prospect[]>([]);const [analyzed,setAnalyzed]=useState(0);const [searched,setSearched]=useState(false);const [configOpen,setConfigOpen]=useState(false);const [importing,setImporting]=useState<Prospect|null>(null);const [history,setHistory]=useState<SearchHistory[]>([]);const [progress,setProgress]=useState({current:0,total:0});const [stopReason,setStopReason]=useState('');const [visibleCount,setVisibleCount]=useState(100);
  async function refreshHistory(){try{const response=await fetch('/api/prospecting/search');const result=response.ok?await response.json() as {searches?:SearchHistory[]}:{searches:[]};setHistory(result.searches||[])}catch{}}
  useEffect(()=>{let mounted=true;fetch('/api/prospecting/search').then(async response=>response.ok?await response.json() as {searches?:SearchHistory[]}:{searches:[]}).then(result=>{if(mounted)setHistory(result.searches||[])}).catch(()=>undefined);return()=>{mounted=false;controllerRef.current?.abort()}},[]);
  const existingIds=useMemo(()=>new Set(data.leads.map(lead=>lead.externalId).filter(Boolean)),[data.leads]);
  const existingNames=useMemo(()=>new Set(data.leads.map(lead=>normalize(lead.company))),[data.leads]);
  const duplicates=results.filter(item=>existingIds.has(item.id)||existingNames.has(normalize(item.name))).length;
  const sortedResults=useMemo(()=>[...results].sort((a,b)=>sort==='reviews'?b.reviewCount-a.reviewCount:sort==='rating'?b.rating-a.rating:sort==='name'?a.name.localeCompare(b.name,'pt-BR'):b.score-a.score||b.reviewCount-a.reviewCount),[results,sort]);
  const visibleResults=sortedResults.slice(0,visibleCount);

  async function search(event?:React.FormEvent){
    event?.preventDefault();if(!connection.connection.connected){setConfigOpen(true);return}
    const selectedCategories=splitEntries(categoryInput);const selectedLocations=splitEntries(locationInput);if(!selectedCategories.length||!selectedLocations.length){setError('Informe ao menos uma categoria e uma localização, usando uma por linha.');return}
    controllerRef.current?.abort();const controller=new AbortController();controllerRef.current=controller;const target=Number(targetCount);const scanLimit=Math.min(10000,Math.max(500,target*5));let cursor:Cursor|undefined;let searchId='';let totalAnalyzed=0;let reason='';const found=new Map<string,Prospect>();
    setSearching(true);setError('');setSearched(true);setResults([]);setAnalyzed(0);setProgress({current:0,total:selectedCategories.length*selectedLocations.length});setStopReason('');setVisibleCount(100);
    try{
      while(!controller.signal.aborted){
        const response=await fetch('/api/prospecting/search',{method:'POST',headers:{'content-type':'application/json'},signal:controller.signal,body:JSON.stringify({categories:selectedCategories,locations:selectedLocations,minRating:Number(minRating),minReviews:Number(minReviews),phoneOnly,websitePresence,businessSize,operationalOnly,cursor,searchId:searchId||undefined})});
        const result=await response.json() as Batch;if(!response.ok)throw new Error(result.error||'Não foi possível pesquisar.');searchId=result.searchId;totalAnalyzed+=result.analyzed;
        for(const item of result.matches||[])found.set(item.id,item);setResults([...found.values()]);setAnalyzed(totalAnalyzed);setProgress(result.queryProgress);
        if(found.size>=target){reason=`Meta de ${target.toLocaleString('pt-BR')} resultados atingida.`;break}
        if(totalAnalyzed>=scanLimit){reason=`Limite de ${scanLimit.toLocaleString('pt-BR')} empresas analisadas atingido.`;break}
        if(result.exhausted||!result.nextCursor){reason='Todas as combinações de categoria e localização foram analisadas.';break}
        cursor=result.nextCursor;await sleep(180);
      }
      if(controller.signal.aborted)reason='Busca interrompida. Os resultados encontrados foram mantidos.';
      setStopReason(reason);
    }catch(reasonValue){if((reasonValue as {name?:string})?.name==='AbortError')setStopReason('Busca interrompida. Os resultados encontrados foram mantidos.');else setError(reasonValue instanceof Error?reasonValue.message:'Não foi possível pesquisar.')}finally{if(controllerRef.current===controller){controllerRef.current=null;setSearching(false)}void refreshHistory()}
  }
  function stop(){controllerRef.current?.abort()}
  function reuse(item:SearchHistory){setCategoryInput(item.category.split(' · ').join('\n'));setLocationInput(item.location.split(' · ').join('\n'));setMinRating(String(item.minRating));setMinReviews(String(item.minReviews));window.scrollTo({top:0,behavior:'smooth'})}
  function exportCsv(){const cell=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;const rows=[['Empresa','Categoria','Endereço','Telefone','Nota','Avaliações','Porte estimado','Site','Google Maps'],...sortedResults.map(item=>[item.name,item.category,item.address,item.phone,item.rating,item.reviewCount,sizeLabels[item.size],item.websiteUrl,item.mapsUrl])];const blob=new Blob(['\ufeff'+rows.map(row=>row.map(cell).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`prospeccao-artweb-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}
  function addLead(form:FormData){if(!importing)return;const now=new Date();const nextAction=new Date(now.getTime()+2*86400000).toISOString().slice(0,10);const score=importing.score;const potential:Importance=score>=80?'Crítica':score>=65?'Alta':score>=50?'Média':'Baixa';const company=String(form.get('company')||importing.name).trim();const lead:Lead={id:crypto.randomUUID(),company,contact:String(form.get('contact')||''),email:'',phone:String(form.get('phone')||importing.phone),whatsapp:'',instagram:'',site:importing.websiteUrl,segment:String(form.get('segment')||importing.category),city:String(form.get('city')||splitEntries(locationInput)[0]||''),source:'Prospecção Google Places',notes:String(form.get('notes')||''),potential,status:'Encontrado',nextAction,created:now.toISOString().slice(0,10),updated:now.toISOString().slice(0,10),externalId:importing.id,rating:importing.rating,reviewCount:importing.reviewCount,mapsUrl:importing.mapsUrl};const log:Activity={id:crypto.randomUUID(),type:'lead.prospected',entityType:'lead',entityId:lead.id,description:`${company} foi encontrado na prospecção e adicionado ao CRM.`,created:now.toISOString()};onCommit({...data,leads:[lead,...data.leads],activities:[log,...data.activities]});setImporting(null)}

  return <div className="prospecting-panel">
    <div className="prospecting-intro"><div><span>BUSCA EM LARGA ESCALA</span><h2>Encontre clientes com filtros precisos</h2><p>Combine categorias e regiões, filtre presença de site e acompanhe milhares de resultados em uma única busca.</p></div><button className="subtle-button" onClick={()=>setConfigOpen(true)}><Settings2/>Configurar fonte</button></div>
    <form className="prospecting-filter-panel" onSubmit={search}>
      <div className="prospecting-filter-head"><div><strong>Parâmetros da busca</strong><span>Use uma categoria ou localização por linha. A busca combina todas elas automaticamente.</span></div><button type="button" onClick={()=>setCategoryInput(categories.join('\n'))}>Usar {categories.length} categorias sugeridas</button></div>
      <div className="prospecting-query-grid"><label>Categorias<textarea value={categoryInput} onChange={event=>setCategoryInput(event.target.value)} rows={4} placeholder="Clínicas odontológicas&#10;Academias e estúdios" required/></label><label>Localizações<textarea value={locationInput} onChange={event=>setLocationInput(event.target.value)} rows={4} placeholder="Campinas, SP&#10;Jundiaí, SP&#10;São Paulo, SP" required/></label></div>
      <div className="prospecting-filter-grid">
        <label>Presença de site<select value={websitePresence} onChange={event=>setWebsitePresence(event.target.value)}><option value="without">Sem site</option><option value="with">Com site</option><option value="any">Qualquer situação</option></select></label>
        <label>Porte estimado<select value={businessSize} onChange={event=>setBusinessSize(event.target.value)} title="Estimado pelo volume de avaliações"><option value="any">Todos os portes</option><option value="local">Local · até 49 avaliações</option><option value="small">Pequeno · 50–199</option><option value="medium">Médio · 200–999</option><option value="large">Grande · 1.000+</option></select></label>
        <label>Nota mínima<select value={minRating} onChange={event=>setMinRating(event.target.value)}><option value="0">Qualquer nota</option><option value="4">4,0+</option><option value="4.3">4,3+</option><option value="4.5">4,5+</option><option value="4.7">4,7+</option><option value="4.8">4,8+</option></select></label>
        <label>Avaliações mínimas<input type="number" value={minReviews} onChange={event=>setMinReviews(event.target.value)} min="0" max="100000"/></label>
        <label>Quantidade alvo<select value={targetCount} onChange={event=>setTargetCount(event.target.value)}><option value="100">Até 100</option><option value="250">Até 250</option><option value="500">Até 500</option><option value="1000">Até 1.000</option><option value="2000">Até 2.000</option></select></label>
      </div>
      <div className="prospecting-filter-actions"><div><label><input type="checkbox" checked={phoneOnly} onChange={event=>setPhoneOnly(event.target.checked)}/><span>Somente com telefone</span></label><label><input type="checkbox" checked={operationalOnly} onChange={event=>setOperationalOnly(event.target.checked)}/><span>Somente em operação</span></label></div><small>O porte é uma estimativa pelo volume de avaliações. A quantidade disponível depende da cobertura do Google Places e as consultas podem gerar cobrança.</small>{searching?<button type="button" className="prospecting-stop" onClick={stop}><X/>Interromper busca</button>:<button className="violet-button prospecting-search"><Search/>Localizar clientes</button>}</div>
    </form>
    {!connection.loading&&!connection.connection.connected&&<section className="prospecting-gate"><KeyRound/><div><strong>Conecte uma fonte de empresas</strong><p>Cadastre uma chave do Google Places para iniciar buscas. A chave do Gemini não é usada nessa ferramenta.</p></div><button className="violet-button" onClick={()=>setConfigOpen(true)}>Configurar Google Places</button></section>}
    {error&&<div className="prospecting-error"><CircleAlert/><span>{error}</span><button onClick={()=>void search()}>Tentar novamente</button></div>}
    {(searching||stopReason)&&searched&&!error&&<section className="prospecting-progress"><div><span>{searching?<><LoaderCircle/>Busca em andamento</>:<><Check/>Busca concluída</>}</span><strong>{results.length.toLocaleString('pt-BR')} encontrados de {Number(targetCount).toLocaleString('pt-BR')}</strong><small>{searching?`Analisando combinação ${progress.current} de ${progress.total}`:stopReason}</small></div><div className="prospecting-progress-track"><i style={{width:`${Math.min(100,(results.length/Number(targetCount))*100)}%`}}/></div></section>}
    {searched&&!error&&<div className="prospecting-kpis"><div><small>Empresas analisadas</small><strong>{analyzed.toLocaleString('pt-BR')}</strong></div><div><small>Clientes encontrados</small><strong>{results.length.toLocaleString('pt-BR')}</strong></div><div><small>Nota média</small><strong>{results.length?(results.reduce((sum,item)=>sum+item.rating,0)/results.length).toFixed(1):'—'}</strong></div><div><small>Já estavam no CRM</small><strong>{duplicates.toLocaleString('pt-BR')}</strong></div></div>}
    {!searching&&searched&&!error&&!results.length?<section className="prospecting-empty"><Search/><h3>Nenhum cliente corresponde aos filtros</h3><p>Reduza a nota mínima, altere a presença de site ou acrescente novas categorias e regiões.</p></section>:results.length>0?<div className="prospecting-results"><header><div><strong>{results.length.toLocaleString('pt-BR')} clientes encontrados</strong><span>Resultados duplicados entre categorias e regiões foram removidos.</span></div><div className="prospecting-result-tools"><label>Ordenar<select value={sort} onChange={event=>setSort(event.target.value as Sort)}><option value="score">Potencial</option><option value="reviews">Mais avaliações</option><option value="rating">Maior nota</option><option value="name">Nome</option></select></label><button onClick={exportCsv}><Download/>Exportar CSV</button></div></header><div className="prospecting-table"><div className="prospecting-row prospecting-table-head"><span>Empresa</span><span>Reputação</span><span>Contato</span><span>Oportunidade</span><span/></div>{visibleResults.map(item=>{const duplicate=existingIds.has(item.id)||existingNames.has(normalize(item.name));return <article className="prospecting-row" key={item.id}><div className="prospecting-company"><i>{item.name.slice(0,1).toUpperCase()}</i><span><strong>{item.name}</strong><small><MapPin/>{item.address||'Endereço não informado'}</small><em>{item.category} · porte {sizeLabels[item.size].toLowerCase()}</em></span></div><div className="prospecting-rating"><strong><Star/>{item.rating.toFixed(1)}</strong><small>{item.reviewCount.toLocaleString('pt-BR')} avaliações</small></div><div className="prospecting-contact"><span><Phone/>{item.phone||'Sem telefone'}</span>{item.websiteUrl?<a href={item.websiteUrl} target="_blank" rel="noreferrer"><Globe2/>Abrir site</a>:item.mapsUrl&&<a href={item.mapsUrl} target="_blank" rel="noreferrer">Ver no mapa<ExternalLink/></a>}</div><div className="prospecting-score"><strong>{item.score}</strong><span>{item.score>=80?'Alta':item.score>=65?'Boa':'Revisar'}</span><em>{item.websiteUrl?'Site identificado':'Sem site identificado'}</em></div><div>{duplicate?<button className="already-added" disabled><Check/>Já está no CRM</button>:<button className="violet-button" onClick={()=>setImporting(item)}><Plus/>Adicionar lead</button>}</div></article>})}</div>{visibleCount<sortedResults.length&&<button className="prospecting-more" onClick={()=>setVisibleCount(value=>value+100)}>Mostrar mais 100 resultados</button>}</div>:!searched?<section className="prospecting-empty prospecting-start"><Building2/><h3>Comece pelas categorias e regiões</h3><p>Adicione várias linhas para ampliar a cobertura. O ArtWeb fará a busca em lotes e eliminará resultados repetidos.</p></section>:null}
    {history.length>0&&<section className="prospecting-history"><h3><History/>Pesquisas recentes</h3><div>{history.map(item=><button onClick={()=>reuse(item)} key={item.id}><strong>{item.category}</strong><span>{item.location} · {item.minRating}+ · {item.resultCount} resultados</span><time>{new Date(item.createdAt).toLocaleDateString('pt-BR')}</time></button>)}</div></section>}
    <Dialog open={configOpen} onOpenChange={setConfigOpen}><DialogContent className="app-dialog ai-config-dialog"><DialogHeader><DialogTitle>Configurar fonte de empresas</DialogTitle><DialogDescription>Conecte o Google Places ao módulo de prospecção.</DialogDescription></DialogHeader>{connection.loading?<div className="prospecting-loading"><LoaderCircle/>Carregando…</div>:<PlacesConnectionForm state={connection.connection} onSaved={async()=>{await connection.refresh();setConfigOpen(false)}}/>}</DialogContent></Dialog>
    <Dialog open={!!importing} onOpenChange={open=>!open&&setImporting(null)}><DialogContent className="app-dialog wide-dialog"><DialogHeader><DialogTitle>Adicionar oportunidade ao CRM</DialogTitle><DialogDescription>Revise os dados antes de criar o lead.</DialogDescription></DialogHeader>{importing&&<form action={addLead} className="form-grid"><div className="prospect-preview"><span><Star/>{importing.rating.toFixed(1)} · {importing.reviewCount} avaliações · porte {sizeLabels[importing.size].toLowerCase()}</span><em>{importing.websiteUrl?'Site identificado':'Sem site identificado'}</em></div><div className="form-row"><label>Empresa<input name="company" defaultValue={importing.name} required/></label><label>Contato responsável<input name="contact" placeholder="Pesquisar depois"/></label></div><div className="form-row"><label>Telefone<input name="phone" defaultValue={importing.phone}/></label><label>Cidade ou região<input name="city" defaultValue={splitEntries(locationInput)[0]||''}/></label></div><label>Segmento<input name="segment" defaultValue={importing.category}/></label><label>Observações<textarea name="notes" rows={4} defaultValue={`Nota ${importing.rating.toFixed(1)} com ${importing.reviewCount} avaliações. Endereço: ${importing.address}. ${importing.websiteUrl?`Site: ${importing.websiteUrl}. `:''}${importing.mapsUrl?`Google Maps: ${importing.mapsUrl}`:''}`}/></label><DialogFooter><button type="button" className="subtle-button dialog-button" onClick={()=>setImporting(null)}>Cancelar</button><button className="violet-button">Adicionar ao pipeline</button></DialogFooter></form>}</DialogContent></Dialog>
  </div>;
}
