'use client';

import { useRef, useState, type CSSProperties } from 'react';
import { Bell, Bot, Brain, Check, Download, ImagePlus, LayoutTemplate, LogOut, MapPinned, Monitor, Moon, Palette, ShieldCheck, Sun, Trash2 } from 'lucide-react';
import type { AuthUser } from '@/lib/auth';
import { monochromeAccents, type Activity, type Data, type Preferences } from '@/lib/model';
import { AIConnectionSettings } from '@/components/os/agent-chat';
import { ProspectingConnectionSettings } from '@/components/os/prospecting';

function activity(type:string,description:string):Activity{return{id:crypto.randomUUID(),type,entityType:'settings',entityId:'workspace',description,created:new Date().toISOString()}}

async function resizePhoto(file:File){
  if(!file.type.startsWith('image/'))throw new Error('Selecione uma imagem válida.');
  if(file.size>10*1024*1024)throw new Error('A imagem deve ter no máximo 10 MB.');
  const url=URL.createObjectURL(file);
  try{
    const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const item=new Image();item.onload=()=>resolve(item);item.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));item.src=url});
    const size=Math.min(image.naturalWidth,image.naturalHeight);const left=(image.naturalWidth-size)/2;const top=(image.naturalHeight-size)/2;
    const canvas=document.createElement('canvas');canvas.width=384;canvas.height=384;const context=canvas.getContext('2d');if(!context)throw new Error('Não foi possível processar a imagem.');
    context.drawImage(image,left,top,size,size,0,0,384,384);return canvas.toDataURL('image/jpeg',.84);
  }finally{URL.revokeObjectURL(url)}
}

export function ProfileView({data,user,onCommit}:{data:Data;user:AuthUser;onCommit:(data:Data)=>void}){
  const input=useRef<HTMLInputElement>(null);const [error,setError]=useState('');const name=data.profile.displayName||user.name;const initials=name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();
  async function upload(file?:File){if(!file)return;setError('');try{const avatarDataUrl=await resizePhoto(file);onCommit({...data,profile:{...data.profile,avatarDataUrl},activities:[activity('profile.photo_changed','Foto do perfil atualizada.'),...data.activities]})}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível alterar a foto.')}}
  function save(form:FormData){const displayName=String(form.get('displayName')||'').trim();const title=String(form.get('title')||'').trim();const bio=String(form.get('bio')||'').trim();onCommit({...data,profile:{...data.profile,displayName,title,bio},activities:[activity('profile.updated','Informações do perfil atualizadas.'),...data.activities]})}
  function removePhoto(){onCommit({...data,profile:{...data.profile,avatarDataUrl:''},activities:[activity('profile.photo_removed','Foto do perfil removida.'),...data.activities]})}
  return <div className="page-content settings-page"><div className="page-heading"><div><div className="eyebrow">IDENTIDADE</div><h1>Seu perfil<span className="wave">✳</span></h1><p>Personalize como você aparece no ArtWeb OS.</p></div></div><section className="settings-card profile-card"><div className="profile-photo-block"><div className="profile-photo">{data.profile.avatarDataUrl?<img src={data.profile.avatarDataUrl} alt="Foto do perfil"/>:<span>{initials||'AW'}</span>}</div><div><h2>Foto do perfil</h2><p>JPG, PNG ou WebP. A imagem será recortada e otimizada automaticamente.</p><div className="profile-photo-actions"><button className="subtle-button" onClick={()=>input.current?.click()}><ImagePlus/>Alterar foto</button>{data.profile.avatarDataUrl&&<button className="danger-text" onClick={removePhoto}><Trash2/>Remover</button>}</div><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={event=>void upload(event.target.files?.[0])}/>{error&&<small className="field-error">{error}</small>}</div></div><form action={save} className="profile-form form-grid"><div className="form-row"><label>Nome de exibição<input name="displayName" defaultValue={name} required/></label><label>Cargo ou função<input name="title" defaultValue={data.profile.title} placeholder="Ex.: Diretor criativo"/></label></div><label>E-mail da conta<input value={user.email} disabled readOnly/><small>O e-mail é usado para entrar e não pode ser alterado aqui.</small></label><label>Sobre você<textarea name="bio" rows={5} defaultValue={data.profile.bio} placeholder="Conte brevemente sobre seu papel e área de atuação." maxLength={360}/></label><div className="profile-form-footer"><span>Até 360 caracteres</span><button className="violet-button">Salvar perfil</button></div></form></section></div>
}

export function SettingsView({data,onCommit}:{data:Data;onCommit:(data:Data)=>void}){
  const preferences=data.preferences;
  function update(patch:Partial<Preferences>){onCommit({...data,preferences:{...preferences,...patch}})}
  function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`artweb-os-backup-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url)}
  async function logoutAll(){const response=await fetch('/api/auth/logout-all',{method:'POST'});if(response.ok)window.location.reload()}
  return <div className="page-content settings-page"><div className="page-heading"><div><div className="eyebrow">PREFERÊNCIAS DO WORKSPACE</div><h1>Configurações<span className="wave">✳</span></h1><p>Ajuste o ArtWeb OS ao seu modo de trabalhar.</p></div></div><div className="settings-layout"><nav className="settings-index"><a href="#appearance"><Palette/>Aparência</a><a href="#assistant"><Bot/>Assistente</a><a href="#prospecting"><MapPinned/>Prospecção</a><a href="#experience"><LayoutTemplate/>Experiência</a><a href="#notifications"><Bell/>Notificações</a><a href="#ai"><Brain/>Inteligência</a><a href="#security"><ShieldCheck/>Segurança e dados</a></nav><div className="settings-sections">
    <SettingsSection id="appearance" icon={Palette} title="Aparência" detail="Tema, contraste e identidade visual do aplicativo."><div className="theme-options">{([{value:'dark',label:'Escuro',icon:Moon},{value:'light',label:'Claro',icon:Sun},{value:'system',label:'Sistema',icon:Monitor}] as const).map(option=><button className={preferences.theme===option.value?'active':''} onClick={()=>update({theme:option.value})} key={option.value}><option.icon/><span>{option.label}</span>{preferences.theme===option.value&&<Check/>}</button>)}</div><SettingRow label="Tom de destaque" detail="Escolha um tom neutro para botões, foco e navegação ativa."><div className="accent-control">{monochromeAccents.map((accent,index)=><button type="button" className={`accent-swatch ${preferences.accent.toUpperCase()===accent?'active':''}`} style={{'--swatch':accent} as CSSProperties} onClick={()=>update({accent})} aria-label={`Tom ${index+1}`} aria-pressed={preferences.accent.toUpperCase()===accent} key={accent}/>)}</div></SettingRow></SettingsSection>
    <SettingsSection id="assistant" icon={Bot} title="Assistente" detail="Conecte a IA que responderá dentro do seu workspace."><AIConnectionSettings/></SettingsSection>
    <SettingsSection id="prospecting" icon={MapPinned} title="Prospecção" detail="Conecte a fonte usada para encontrar empresas e oportunidades."><ProspectingConnectionSettings/></SettingsSection>
    <SettingsSection id="experience" icon={LayoutTemplate} title="Experiência" detail="Defina a densidade e o ponto de partida do workspace."><SettingRow label="Densidade" detail="Controle o espaço entre elementos."><select value={preferences.density} onChange={event=>update({density:event.target.value as Preferences['density']})}><option value="comfortable">Confortável</option><option value="compact">Compacta</option></select></SettingRow><SettingRow label="Tela inicial" detail="Módulo aberto depois do login."><select value={preferences.startView} onChange={event=>update({startView:event.target.value})}>{['Visão geral','CRM','Clientes','Projetos','Tarefas','Conhecimento'].map(view=><option key={view}>{view}</option>)}</select></SettingRow><SettingRow label="Primeiro dia da semana" detail="Usado em calendários e relatórios."><select value={preferences.weekStartsOn} onChange={event=>update({weekStartsOn:event.target.value as Preferences['weekStartsOn']})}><option value="sunday">Domingo</option><option value="monday">Segunda-feira</option></select></SettingRow></SettingsSection>
    <SettingsSection id="notifications" icon={Bell} title="Notificações" detail="Receba apenas alertas que pedem uma ação."><Toggle label="Prazos e tarefas atrasadas" detail="Avisos de tarefas vencendo ou atrasadas." checked={preferences.deadlineNotifications} onChange={value=>update({deadlineNotifications:value})}/><Toggle label="CRM e retornos comerciais" detail="Leads aguardando resposta ou próxima ação." checked={preferences.commercialNotifications} onChange={value=>update({commercialNotifications:value})}/><Toggle label="Resumo por e-mail" detail="Preparado para o serviço de e-mail da próxima integração." checked={preferences.emailNotifications} onChange={value=>update({emailNotifications:value})}/></SettingsSection>
    <SettingsSection id="ai" icon={Brain} title="Inteligência e memória" detail="Controle a recuperação contextual e o consumo de contexto."><SettingRow label="Orçamento de contexto" detail="Limita quantos itens relevantes podem ser enviados à IA."><select value={preferences.contextBudget} onChange={event=>update({contextBudget:event.target.value as Preferences['contextBudget']})}><option value="minimal">Mínimo</option><option value="balanced">Equilibrado</option><option value="extended">Estendido</option></select></SettingRow><Toggle label="Sugerir memórias" detail="Permite sugerir a promoção de decisões e aprendizados importantes." checked={preferences.memorySuggestions} onChange={value=>update({memorySuggestions:value})}/></SettingsSection>
    <SettingsSection id="security" icon={ShieldCheck} title="Segurança e dados" detail="Sessões, portabilidade e próximos controles de proteção."><div className="security-actions"><button className="subtle-button" onClick={exportData}><Download/>Exportar meus dados</button><button className="danger-outline" onClick={()=>void logoutAll()}><LogOut/>Encerrar todas as sessões</button></div><div className="settings-analysis"><h3>Configurações previstas</h3><p>A análise do sistema recomenda adicionar em seguida: recuperação de senha, verificação de e-mail, autenticação em dois fatores, gestão de dispositivos, idioma e fuso horário, regras de retenção, backups agendados, permissões por equipe, integrações e trilha de auditoria exportável.</p></div></SettingsSection>
  </div></div></div>
}

function SettingsSection({id,icon:Icon,title,detail,children}:{id:string;icon:typeof Palette;title:string;detail:string;children:React.ReactNode}){return <section className="settings-card settings-section" id={id}><header><span><Icon/></span><div><h2>{title}</h2><p>{detail}</p></div></header><div className="settings-content">{children}</div></section>}
function SettingRow({label,detail,children}:{label:string;detail:string;children:React.ReactNode}){return <div className="setting-row"><div><strong>{label}</strong><p>{detail}</p></div>{children}</div>}
function Toggle({label,detail,checked,onChange}:{label:string;detail:string;checked:boolean;onChange:(checked:boolean)=>void}){return <div className="setting-row"><div><strong>{label}</strong><p>{detail}</p></div><button className={`switch ${checked?'on':''}`} role="switch" aria-checked={checked} onClick={()=>onChange(!checked)}><i/></button></div>}
